/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_referencias;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lsfer
 */
public class VentanaMod_BusCategoria extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMod_BusCategoria
     */
    public VentanaMod_BusCategoria() {
        initComponents();
        actualizarTabla();
    }
    
    public void actualizarTabla() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jTCategoria.setModel(modelo);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            //
            
            String sql = "SELECT id_categoria, nombre, descripcion FROM categoria";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            modelo.addColumn("ID Categoria");
            modelo.addColumn("Nombre");
            modelo.addColumn("Descripción");
            
            while(rs.next()) {
                Object[] filas = new Object[cantidadColumnas]; //ya que la tabla trabaja con objetos, metemos todo en objetos
                
                for (int i=0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                
                modelo.addRow(filas);
            }
            
            con.close();
            
        } catch (SQLException ex) {
            JOptionPane.showInputDialog("Error:" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTCategoria = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboColumnas = new javax.swing.JComboBox<>();
        bBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tIDCategoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        bModificar = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();
        tBuscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Categoria", "Nombre", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTCategoria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 74, 463, 387));

        jLabel1.setText("Buscar por:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 20, -1, -1));

        comboColumnas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Categoria", "Nombre" }));
        getContentPane().add(comboColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 15, -1, -1));

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(bBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 12, 123, -1));

        jLabel2.setText("ID Categoria:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 91, -1, -1));

        tIDCategoria.setEnabled(false);
        getContentPane().add(tIDCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 87, 127, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 152, -1, -1));
        getContentPane().add(tNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 148, 127, -1));

        jLabel4.setText("Descripción:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 202, -1, -1));

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        jScrollPane2.setViewportView(taDescripcion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 202, -1, 154));

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });
        getContentPane().add(bModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 410, -1, -1));

        bCerrar.setText("Cerrar");
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 410, -1, -1));
        getContentPane().add(tBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 16, 123, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("SISLIB.");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("SISLIB.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(711, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(358, 358, 358)
                    .addComponent(jLabel5)
                    .addContainerGap(359, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(438, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(216, 216, 216)
                    .addComponent(jLabel5)
                    .addContainerGap(216, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCerrarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        String texto = tBuscar.getText();
        String campo = comboColumnas.getSelectedItem().toString();
        String where = "";
        
        if (campo.equals("ID Categoria")) {
            where = " WHERE id_categoria = " + texto;
        } else if (campo.equals("Nombre")) {
            where = " WHERE nombre = '" + texto + "'";
        } 
        
        if ("".equals(texto)) {
            where = "";
        }
        
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jTCategoria.setModel(modelo);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            
            String sql = "SELECT id_categoria, nombre, descripcion FROM categoria" + where;
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            modelo.addColumn("ID Categoria");
            modelo.addColumn("Nombre");
            modelo.addColumn("Descripción");
            
            while(rs.next()) {
                Object[] filas = new Object[cantidadColumnas]; //ya que la tabla trabaja con objetos, metemos todo en objetos
                
                for (int i=0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                
                modelo.addRow(filas);
            }
            
            con.close();
            
        } catch (SQLException ex) {
            JOptionPane.showInputDialog("Error:" + ex);
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void jTCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCategoriaMouseClicked
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            
            int Fila = jTCategoria.getSelectedRow();
            String codigo = jTCategoria.getValueAt(Fila, 0).toString();
            
            ps = con.prepareStatement("SELECT id_categoria, nombre, descripcion FROM categoria WHERE id_categoria = ?");
            ps.setInt(1, Integer.parseInt(codigo));
            rs = ps.executeQuery();
            
            while (rs.next()) {
                tIDCategoria.setText(rs.getString("id_categoria"));
                tNombre.setText(rs.getString("nombre"));
                taDescripcion.setText(rs.getString("descripcion"));
            }
            
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showInputDialog("Ocurrio un error: " + ex.toString());
        }
    }//GEN-LAST:event_jTCategoriaMouseClicked

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        if (!tIDCategoria.getText().equals("")) {
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            PreparedStatement ps = null;
            
            try {
                ps = con.prepareStatement("UPDATE categoria SET nombre=?, descripcion=? WHERE id_categoria=?");
                ps.setString(1, tNombre.getText());
                ps.setString(2, taDescripcion.getText());
                ps.setInt(3, Integer.parseInt(tIDCategoria.getText()));
                
                int res = ps.executeUpdate();
                
                if(res > 0) {
                    JOptionPane.showInputDialog("Categoria modificada");
                } else {
                    JOptionPane.showInputDialog("Ocurrio un error al modificar");
                }
                
                con.close();
            } catch (Exception e) {
                JOptionPane.showInputDialog("Error: " + e.toString());
            }
        } else {
            JOptionPane.showInputDialog("Seleccione un elemento de la tabla para poder realizar el cambio");
        }
        
        actualizarTabla();
    }//GEN-LAST:event_bModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMod_BusCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMod_BusCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMod_BusCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMod_BusCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMod_BusCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bModificar;
    private javax.swing.JComboBox<String> comboColumnas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTCategoria;
    private javax.swing.JTextField tBuscar;
    private javax.swing.JTextField tIDCategoria;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextArea taDescripcion;
    // End of variables declaration//GEN-END:variables
}
