/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_referencias;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lsfer
 */
public class VentanaMod_BusTextos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMod_BusTextos
     */
    public VentanaMod_BusTextos() {
        initComponents();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboColumnas = new javax.swing.JComboBox<>();
        tBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabTextos = new javax.swing.JTable();
        bBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tIDTexto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tAutor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tTitulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tNoPaginas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tFechaEd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tEditorial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tIDCategoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taFragTexto = new javax.swing.JTextPane();
        bModificar = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Buscar por:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 21, -1, -1));

        comboColumnas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Texto", "ISBN", "Autor", "Titulo", "Editorial", "Fragmento Texto" }));
        getContentPane().add(comboColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 16, 191, -1));
        getContentPane().add(tBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 17, 192, -1));

        tabTextos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Texto", "ISBN", "Autor", "Título", "No. de Páginas", "Fecha Ed.", "Editorial", "ID Categoría", "Frag. Texto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabTextos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTextosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabTextos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 63, 676, -1));

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(bBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 13, 144, -1));

        jLabel2.setText("ID Texto: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 21, -1, -1));

        tIDTexto.setEnabled(false);
        getContentPane().add(tIDTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 17, 81, -1));

        jLabel3.setText("ISBN:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 67, -1, -1));
        getContentPane().add(tISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 63, 211, -1));

        jLabel4.setText("Autor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 117, -1, -1));
        getContentPane().add(tAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 113, 211, -1));

        jLabel5.setText("Título:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 163, -1, -1));
        getContentPane().add(tTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 159, 211, -1));

        jLabel6.setText("No. de Páginas:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 213, -1, -1));
        getContentPane().add(tNoPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 209, 211, -1));

        jLabel7.setText("Fecha edición:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 255, -1, -1));
        getContentPane().add(tFechaEd, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 251, 211, -1));

        jLabel8.setText("Editorial:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 297, -1, -1));
        getContentPane().add(tEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 293, 211, -1));

        jLabel9.setText("ID Categoría:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 339, -1, -1));
        getContentPane().add(tIDCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 335, 211, -1));

        jLabel10.setText("Fragmento Texto:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 377, -1, -1));

        jScrollPane2.setViewportView(taFragTexto);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 377, 246, 121));

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });
        getContentPane().add(bModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 510, 151, -1));

        bCerrar.setText("Cerrar");
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 154, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setText("SISLIB.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(973, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addContainerGap(487, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        this.dispose();
        actualizarTabla();
    }//GEN-LAST:event_bCerrarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        String texto = tBuscar.getText();
        String campo = comboColumnas.getSelectedItem().toString();
        String where = "";
        
        if (campo.equals("ID Texto")) {
            where = " WHERE id_texto = " + texto;
        } else if (campo.equals("ISBN")) {
            where = " WHERE isbn = '" + texto + "'";
        } else if (campo.equals("Autor")) {
            where = " WHERE autor LIKE '%" + texto + "%'";
        } else if (campo.equals("Titulo")) {
            where = " WHERE titulo LIKE '%" + texto + "%'";
        } else if (campo.equals("Editorial")) {
            where = " WHERE editorial LIKE '%" + texto + "%'";
        } else if (campo.equals("Fragmento Texto")) {
            where = " WHERE fragmento_texto LIKE '%" + texto + "%'";
        }
        
        if ("".equals(texto)) {
            where = "";
        }
        
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            tabTextos.setModel(modelo);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            
            String sql = "SELECT id_texto, isbn, autor, titulo, no_paginas, fecha_edicion, editorial, id_categoria,"
                    + " fragmento_texto FROM texto" + where;
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            modelo.addColumn("ID Texto");
            modelo.addColumn("ISBN");
            modelo.addColumn("Autor");
            modelo.addColumn("Título");
            modelo.addColumn("No. de Páginas");
            modelo.addColumn("Fecha Ed.");
            modelo.addColumn("Editorial");
            modelo.addColumn("ID Categoría");
            modelo.addColumn("Frag. Texto");
            
            while(rs.next()) {
                Object[] filas = new Object[cantidadColumnas]; //ya que la tabla trabaja con objetos, metemos todo en objetos
                
                for (int i=0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                
                modelo.addRow(filas);
            }
            
            con.close();
            
        } catch (SQLException ex) {
            JOptionPane.showInputDialog("Error:" + ex);
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        if (!tIDTexto.getText().equals("")) {
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            PreparedStatement ps = null;
            
            try {
                ps = con.prepareStatement("UPDATE texto SET isbn=?, autor=?, titulo=?, no_paginas=?,"
                        + " fecha_edicion=?, editorial=?, id_categoria=?, fragmento_texto=? WHERE id_texto=?");
                ps.setString(1, tISBN.getText());
                ps.setString(2, tAutor.getText());
                ps.setString(3, tTitulo.getText());
                ps.setString(4, tNoPaginas.getText());
                ps.setString(5, tFechaEd.getText());
                ps.setString(6, tEditorial.getText());
                ps.setInt(7, Integer.parseInt(tIDCategoria.getText()));
                ps.setString(8, taFragTexto.getText());
                ps.setInt(9, Integer.parseInt(tIDTexto.getText()));
                
                int res = ps.executeUpdate();
                
                if(res > 0) {
                    JOptionPane.showInputDialog("Texto modificado");
                } else {
                    JOptionPane.showInputDialog("Ocurrio un error al modificar");
                }
                
                con.close();
            } catch (Exception e) {
                JOptionPane.showInputDialog("Error: " + e.toString());
            }
        } else {
            JOptionPane.showInputDialog("Seleccione un elemento de la tabla para poder realizar el cambio");
        }
        
        actualizarTabla();
    }//GEN-LAST:event_bModificarActionPerformed

    private void tabTextosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTextosMouseClicked
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            
            int Fila = tabTextos.getSelectedRow();
            String codigo = tabTextos.getValueAt(Fila, 0).toString();
            
            ps = con.prepareStatement("SELECT id_texto, isbn, autor, titulo, no_paginas,"
                    + " fecha_edicion, editorial, id_categoria, fragmento_texto FROM texto WHERE id_texto = ?");
            ps.setInt(1, Integer.parseInt(codigo));
            rs = ps.executeQuery();
            
            while (rs.next()) {
                tIDTexto.setText(rs.getString("id_Texto"));
                tISBN.setText(rs.getString("isbn"));
                tAutor.setText(rs.getString("autor"));
                tTitulo.setText(rs.getString("titulo"));
                tNoPaginas.setText(rs.getString("no_paginas"));
                tFechaEd.setText(rs.getString("fecha_edicion"));
                tEditorial.setText(rs.getString("editorial"));
                tIDCategoria.setText(rs.getString("id_categoria"));
                taFragTexto.setText(rs.getString("fragmento_texto"));
            }
            
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showInputDialog("Ocurrio un error: " + ex.toString());
        }
    }//GEN-LAST:event_tabTextosMouseClicked

    public void actualizarTabla() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            tabTextos.setModel(modelo);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            
            String sql = "SELECT id_texto, isbn, autor, titulo, no_paginas, fecha_edicion, editorial, id_categoria,"
                    + " fragmento_texto FROM texto";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            modelo.addColumn("ID Texto");
            modelo.addColumn("ISBN");
            modelo.addColumn("Autor");
            modelo.addColumn("Título");
            modelo.addColumn("No. de Páginas");
            modelo.addColumn("Fecha Ed.");
            modelo.addColumn("Editorial");
            modelo.addColumn("ID Categoría");
            modelo.addColumn("Frag. Texto");
            
            while(rs.next()) {
                Object[] filas = new Object[cantidadColumnas]; //ya que la tabla trabaja con objetos, metemos todo en objetos
                
                for (int i=0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                
                modelo.addRow(filas);
            }
            
            con.close();
            
        } catch (SQLException ex) {
            JOptionPane.showInputDialog("Error:" + ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMod_BusTextos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMod_BusTextos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMod_BusTextos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMod_BusTextos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMod_BusTextos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bModificar;
    private javax.swing.JComboBox<String> comboColumnas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tAutor;
    private javax.swing.JTextField tBuscar;
    private javax.swing.JTextField tEditorial;
    private javax.swing.JTextField tFechaEd;
    private javax.swing.JTextField tIDCategoria;
    private javax.swing.JTextField tIDTexto;
    private javax.swing.JTextField tISBN;
    private javax.swing.JTextField tNoPaginas;
    private javax.swing.JTextField tTitulo;
    private javax.swing.JTextPane taFragTexto;
    private javax.swing.JTable tabTextos;
    // End of variables declaration//GEN-END:variables
}
