/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_referencias;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lsfer
 */
public class VentanaAgregarTexto extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAgregarTexto
     */
    public VentanaAgregarTexto() {
        initComponents();
        consultaCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tIDCategoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tISBN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tNoPaginas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tDia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bCerrar = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taFragTexto = new javax.swing.JTextArea();
        tAño = new javax.swing.JTextField();
        tMes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ComboBDCat = new javax.swing.JComboBox<>();
        tEditorial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ISBN:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 30, -1, -1));
        getContentPane().add(tISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 26, 268, -1));

        jLabel2.setText("Autor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 60, -1, -1));
        getContentPane().add(tAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 56, 268, -1));

        jLabel3.setText("Titulo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 96, -1, -1));
        getContentPane().add(tTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 92, 268, -1));

        jLabel4.setText("No. Páginas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 138, -1, -1));
        getContentPane().add(tNoPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 134, 268, -1));

        jLabel5.setText("Fecha de edición:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 180, -1, -1));
        getContentPane().add(tDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 176, 46, -1));

        jLabel6.setText("Editorial:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 216, -1, -1));

        jLabel7.setText("ID Categoria:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 252, -1, -1));

        jLabel8.setText("Fragmento de Texto:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 284, -1, -1));

        bCerrar.setText("Cerrar");
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 385, -1, -1));

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(bAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 385, -1, -1));

        taFragTexto.setColumns(20);
        taFragTexto.setRows(5);
        jScrollPane1.setViewportView(taFragTexto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 284, 268, -1));
        getContentPane().add(tAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 176, 59, -1));
        getContentPane().add(tMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 176, 46, -1));

        jLabel9.setText("DD");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 180, -1, -1));

        jLabel10.setText("MM");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 180, -1, -1));

        jLabel11.setText("AAAA");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 180, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setText("SISLIB.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBDCat, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(tEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ComboBDCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCerrarActionPerformed
    public void consultaCombo(){
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            //jTCategoria.setModel(modelo);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            
            String sql = "SELECT id_categoria FROM categoria"; //+ where;
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()) {
               
                ComboBDCat.addItem(rs.getString(1));
            }
            
            con.close();
            
        } catch (SQLException ex) {
            JOptionPane.showInputDialog("Error:" + ex);
        }
    }
    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        String isbn, autor, titulo, no_paginas, dia, mes, año, editorial, fragmento_texto;
        int id_categoria;
        isbn = tISBN.getText();
        autor = tAutor.getText();
        titulo = tTitulo.getText();
        no_paginas = tNoPaginas.getText();
        dia = tDia.getText();
        mes = tMes.getText();
        año = tAño.getText();
        editorial = tEditorial.getText();
        fragmento_texto = taFragTexto.getText();
        id_categoria = Integer.parseInt( ComboBDCat.getSelectedItem().toString());
        Altas operacion = new Altas();
        operacion.alta(isbn, autor, titulo, no_paginas, dia, mes, año, editorial, id_categoria, fragmento_texto);
    }//GEN-LAST:event_bAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregarTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBDCat;
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tAutor;
    private javax.swing.JTextField tAño;
    private javax.swing.JTextField tDia;
    private javax.swing.JTextField tEditorial;
    private javax.swing.JTextField tIDCategoria;
    private javax.swing.JTextField tISBN;
    private javax.swing.JTextField tMes;
    private javax.swing.JTextField tNoPaginas;
    private javax.swing.JTextField tTitulo;
    private javax.swing.JTextArea taFragTexto;
    // End of variables declaration//GEN-END:variables
}
